### ISSUE TITLE
Stopped working today.

### ISSUE THREAD

**Issue by wrightc214** [idkclub/dicebot#66]
We kept getting a failure message. I don't recall the exact text. I uninstalled with the intent to reinstall; however, we can't get it to install now.  It worked fine yesterday.

**Comment by arkie** [comment]
Definitely want to apologize for the issue! Currently still investigating, but it seems like the host "@superfly" (https://fly.io) has stop serving requests for the app :|

Will update this issue as triaging continues.

**Comment by arkie** [comment]
I redeployed the exact same code, and it's now up. The issue is that @superfly is an unstable host. I'll leave this issue open with the hope that someone from their team can clarify what their issue is.

Postmortem: **Do not use fly.io.**

**Comment by mrkurt** [comment]
If you post your app details at https://community.fly.io we can help you figure out what went wrong.

**Comment by arkie** [comment]
> If you post your app details at https://community.fly.io we can help you figure out what went wrong.

https://community.fly.io/t/https-dicebot-idk-club-https-dicebot-fly-dev-stopped-service/1592
